name: Run Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fastapi-news-project

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install pipenv
      run: pip install pipenv

    - name: Check Python version (ensure 3.13)
      run: python --version

    - name: Set Pipenv to use the current Python
      run: pipenv --python $(which python3)

    - name: Install dependencies
      run: pipenv install --dev

    - name: Set environment variables for tests
      run: |
        echo "DATABASE_URL=sqlite+aiosqlite:///./test.db" >> $GITHUB_ENV
        echo "SECRET_KEY=TestSecretKey" >> $GITHUB_ENV
        echo "ALGORITHM=HS256" >> $GITHUB_ENV
        echo "ACCESS_TOKEN_EXPIRE_MINUTES=60" >> $GITHUB_ENV

    - name: Run pytest
      run: pipenv run pytest
